# Tanda 2 — Gestión de citas: CU17, CU18, CU22, CU76.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from motor import generar_cu, chrome_path
from comun import P, ACTOR, VISTA, BASE, API, DAO, SQL, TRES, q, upd, ins, fallo_bd

T_CITA = P('Cita', 'tabla')
T_BITACORA = P('Bitacora_Auditoria', 'tabla')
T_NOTIF = P('Notificacion', 'tabla')
T_PARAM = P('Parametro_Global', 'tabla')

# ──────────────────────────── CU17 ────────────────────────────
CU17 = dict(id='CU17', nombre='Gestionando reprogramación de cita', actores=['Paciente'],
  vistas={'Paciente': 'V_Mis_Citas'},
  participantes=[ACTOR, VISTA, P('V_Agendamiento_Cita', 'vista'), *BASE,
                 T_CITA, P('Bloqueo_Agenda', 'tabla'), T_PARAM, T_BITACORA, T_NOTIF],
  principal=[
    'A -> V: seleccionar_cita_vigente(cita_id)',
    'V ->> V: verificar_estado_reprogramable()',
    'V --> A: solicitar_motivo_del_cambio()',
    'A -> V: indicar_motivo(motivo)',
    'V -> V_Agendamiento_Cita: abrir_buscador_en_modo_reprogramacion(cita_id, motivo)',
    f'V_Agendamiento_Cita -> {API}: GET /citas/disponibilidad (especialidad, fecha)',
    f'{API} -> {DAO}: consultar_cupos_disponibles(profesional_id, fecha)',
    *q('Cita', 'cita_id, fecha_hora_inicio, fecha_hora_fin, estado', 'bloques ocupados'),
    f'{DAO} --> {API}: return (matriz de disponibilidad)',
    f'{API} --> V_Agendamiento_Cita: return (HTTP 200 OK: cupos disponibles)',
    'V_Agendamiento_Cita --> A: mostrar_matriz_de_disponibilidad()',
    'A -> V_Agendamiento_Cita: seleccionar_nuevo_bloque(fecha_hora_inicio)',
    f'V_Agendamiento_Cita -> {API}: POST /citas/:id/reprogramar (nuevo_bloque, motivo)',
    f'{API} -> {DAO}: abrir_transaccion_y_bloquear_cita(cita_id)',
    *q('Cita', 'cita_id, estado, fecha_hora_inicio, fecha_hora_fin, paciente_id, profesional_id', '1 cita'),
    f'{DAO} --> {API}: return (cita)',
    f'{API} ->> {API}: verificar_estado_y_titularidad()',
    f'{API} -> {DAO}: leer_parametro(HORAS_MIN_REPROGRAMACION)',
    *q('Parametro_Global', 'clave, valor', 'horas minimas'),
    f'{DAO} --> {API}: return (horas_minimas)',
    f'{API} ->> {API}: validar_anticipacion_minima()',
    f'{API} -> {DAO}: verificar_bloque_libre(nuevo_bloque)',
    *q('Cita', 'cita_id', '0 citas en el bloque'),
    f'{DAO} --> {API}: return (bloque libre)',
    f'{API} -> {DAO}: verificar_bloqueos_de_agenda(profesional_id, nuevo_bloque)',
    *q('Bloqueo_Agenda', 'bloqueo_id, motivo', '0 bloqueos'),
    f'{DAO} --> {API}: return (sin bloqueos)',
    f'{API} -> {DAO}: actualizar_horario(cita_id, nuevo_bloque, AGENDADA)',
    *upd('Cita', 'fecha_hora_inicio, fecha_hora_fin, estado'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} -> {DAO}: registrar_trazabilidad(CITA_REPROGRAMADA, bloque_anterior, bloque_nuevo, motivo)',
    *ins('Bitacora_Auditoria'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} -> {DAO}: notificar_a_ambos_participantes(CITA_REPROGRAMADA)',
    *ins('Notificacion', ' (aviso de reprogramacion)'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} ->> {API}: confirmar_transaccion()',
    f'{API} --> V_Agendamiento_Cita: return (HTTP 200 OK: cita reprogramada)',
    'V_Agendamiento_Cita --> A: mostrar_confirmacion_con_la_nueva_fecha()',
  ],
  excepciones={
    1: dict(cortar='verificar_estado_reprogramable', lineas=[
        '! La cita ya esta realizada, cancelada, con inasistencia o en curso',
        'V --> A: deshabilitar_controles_de_edicion()',
        'A -> V: volver_al_listado_y_elegir_cita_activa()']),
    2: dict(cortar='validar_anticipacion_minima', lineas=[
        '! Solicitud fuera del tiempo minimo de anticipacion configurado',
        f'{API} ->> {API}: revertir_transaccion()',
        f'{API} --> V_Agendamiento_Cita: return (HTTP 409 FUERA_DE_PLAZO)',
        'V_Agendamiento_Cita --> A: notificar_restriccion_temporal_y_denegar_calendario()',
        'A ->> A: mantener_cita_original_o_contactar_a_soporte()']),
    3: dict(cortar='SELECT cita_id FROM Cita', lineas=[
        f'Cita --> {SQL}: return (1 cita tomada por otro proceso)',
        f'{SQL} --> {DAO}: return (resultado)',
        f'{DAO} --> {API}: return (bloque ocupado)',
        '! El bloque fue tomado por otra reserva o cae en un bloqueo de agenda',
        f'{API} ->> {API}: revertir_transaccion()',
        f'{API} --> V_Agendamiento_Cita: return (HTTP 409 BLOQUE_OCUPADO | AGENDA_BLOQUEADA)',
        'V_Agendamiento_Cita --> A: refrescar_matriz_de_disponibilidad()',
        'A -> V_Agendamiento_Cita: seleccionar_nuevo_bloque(fecha_hora_inicio)'],
        reanudar='POST /citas/:id/reprogramar'),
    4: dict(cortar='INSERT INTO Notificacion (aviso de reprogramacion)', lineas=[
        *fallo_bd('Notificacion', 'servicio de notificaciones no disponible'),
        '! Falla el aviso tras guardar: la cita ya quedo reprogramada',
        f'{API} ->> {API}: registrar_error_de_comunicacion()',
        f'{API} ->> {API}: confirmar_transaccion()',
        f'{API} --> V_Agendamiento_Cita: return (HTTP 200 OK: cita reprogramada, aviso pendiente)',
        'V_Agendamiento_Cita --> A: mostrar_nueva_fecha_sin_confirmacion_de_aviso()',
        'A -> V: verificar_en_proximas_consultas()']),
  })

# ──────────────────────────── CU18 ────────────────────────────
CU18 = dict(id='CU18', nombre='Cancelando cita y liberando recursos', actores=['Paciente', 'Profesional'],
  vistas={'Paciente': 'V_Mis_Citas', 'Profesional': 'V_Gestion_Agenda'},
  participantes=[ACTOR, VISTA, *BASE, T_CITA, T_PARAM, T_BITACORA, P('Lista_Espera', 'tabla'), T_NOTIF],
  principal=[
    'A -> V: solicitar_anulacion_de_cita(cita_id)',
    'V --> A: mostrar_dialogo_de_confirmacion()',
    'A -> V: ratificar_anulacion(motivo)',
    'V ->> V: verificar_motivo_no_vacio()',
    f'V -> {API}: POST /citas/:id/transicionar (evento = CANCELAR, motivo)',
    f'{API} -> {DAO}: abrir_transaccion_y_bloquear_cita(cita_id)',
    *q('Cita', 'cita_id, estado, fecha_hora_inicio, paciente_id, profesional_id', '1 cita'),
    f'{DAO} --> {API}: return (cita)',
    f'{API} ->> {API}: verificar_titularidad_del_actor({{A}})',
    f'{API} -> {DAO}: leer_parametro(HORAS_MIN_CANCELACION)',
    *q('Parametro_Global', 'clave, valor', 'horas minimas'),
    f'{DAO} --> {API}: return (horas_minimas)',
    f'{API} ->> {API}: validar_plazo_minimo_de_anticipacion()',
    f'{API} ->> {API}: evaluar_maquina_de_estados(CANCELAR, rol = {{A}})',
    f'{API} -> {DAO}: actualizar_estado(CANCELADA_{{A_MAY}}, motivo)',
    *upd('Cita', 'estado, motivo_cancelacion'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} -> {DAO}: registrar_trazabilidad(CITA_CANCELADA, rol_actor, motivo)',
    *ins('Bitacora_Auditoria'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} -> {DAO}: notificar_a_ambos_participantes(CAMBIO_ESTADO_CITA)',
    *ins('Notificacion', ' (aviso de cancelacion)'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} -> {DAO}: buscar_inscritos_en_lista_de_espera(cita_id)',
    *q('Lista_Espera', 'lista_espera_id, posicion, usuario_id', 'N inscritos'),
    f'{DAO} --> {API}: return (inscritos)',
    f'{API} -> {DAO}: avisar_cupo_liberado(inscritos)',
    *ins('Notificacion', ' (cupo liberado)'),
    *upd('Lista_Espera', 'notificado'),
    f'{DAO} --> {API}: return (cupos_notificados)',
    f'{API} ->> {API}: confirmar_transaccion()',
    f'{API} --> V: return (HTTP 200 OK: cita cancelada, cupos_notificados)',
    'V --> A: mostrar_confirmacion_y_cronograma_actualizado()',
  ],
  excepciones={
    1: dict(cortar='validar_plazo_minimo_de_anticipacion', lineas=[
        '! Anulacion fuera del plazo reglamentario parametrizado',
        f'{API} ->> {API}: revertir_transaccion()',
        f'{API} --> V: return (HTTP 409 FUERA_DE_PLAZO)',
        'V --> A: informar_imposibilidad_de_cancelar_con_poca_antelacion()',
        'A ->> A: desistir_o_contactar_al_centro()']),
    2: dict(cortar='UPDATE Cita SET estado, motivo_cancelacion', lineas=[
        *fallo_bd('Cita'),
        '! Fallo de persistencia al actualizar la cita',
        f'{API} ->> {API}: revertir_transaccion()',
        f'{API} --> V: return (HTTP 500: la anulacion no pudo completarse)',
        'V --> A: solicitar_reintento_manual()',
        'A -> V: ratificar_anulacion(motivo)'],
        reanudar='POST /citas/:id/transicionar'),
    3: dict(cortar='return (HTTP 200 OK: cita cancelada', lineas=[
        '! La vista no logra renderizar el resumen de la operacion',
        'V ->> V: registrar_error_de_carga_en_el_cliente()',
        'V --> A: mostrar_pantalla_incompleta()',
        'A -> V: refrescar_aplicacion()',
        f'V -> {API}: GET /citas/mis-citas',
        f'{API} --> V: return (HTTP 200 OK: listado actualizado)',
        'V --> A: mostrar_la_cita_como_cancelada()']),
    4: dict(cortar='INSERT INTO Notificacion (cupo liberado)', lineas=[
        *fallo_bd('Notificacion', 'servicio de notificaciones no disponible'),
        '! Falla el aviso a la lista de espera: la cancelacion se mantiene',
        f'{API} ->> {API}: registrar_fallo_de_notificacion()',
        f'{API} ->> {API}: confirmar_transaccion()',
        f'{API} --> V: return (HTTP 200 OK: cita cancelada, sin avisos enviados)',
        'V --> A: mostrar_confirmacion_local_de_la_baja()']),
  })

# ──────────────────────────── CU22 ────────────────────────────
CU22 = dict(id='CU22', nombre='Registrando trazabilidad de transiciones de agenda', actores=TRES,
  vistas={'Paciente': 'V_Mis_Citas', 'Profesional': 'V_Gestion_Agenda', 'Administrador': 'V_Gestion_Agenda'},
  participantes=[ACTOR, VISTA, *BASE, T_CITA, T_BITACORA],
  principal=[
    'A -> V: ejecutar_cambio_de_estado_o_reprogramacion(cita_id)',
    f'V -> {API}: POST /citas/:id/transicionar (evento, motivo)',
    f'{API} ->> {API}: verificar_token_y_obtener_actor(usuario_id, rol = {{A}})',
    f'{API} -> {DAO}: abrir_transaccion_y_bloquear_cita(cita_id)',
    *q('Cita', 'cita_id, estado, paciente_id, profesional_id', '1 cita'),
    f'{DAO} --> {API}: return (cita)',
    f'{API} ->> {API}: verificar_estado_no_terminal()',
    f'{API} ->> {API}: capturar_metadatos(usuario_id, rol, momento_evento, ip_origen)',
    f'{API} ->> {API}: exigir_justificacion_en_cancelacion_o_reprogramacion()',
    f'{API} -> {DAO}: aplicar_cambio_de_estado(nuevo_estado)',
    *upd('Cita', 'estado, motivo_cancelacion'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} -> {DAO}: registrar_trazabilidad(accion, responsable, rol, motivo, ip_origen)',
    *ins('Bitacora_Auditoria', ' (accion, entidad_afectada, ip_origen, datos_adicionales, usuario_id)'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} ->> {API}: confirmar_transaccion(cambio y log en la misma transaccion)',
    f'{API} --> V: return (HTTP 200 OK: cambio aplicado y trazado)',
    'V --> A: mostrar_estado_actualizado()',
    'A -> V: consultar_trazabilidad_de_la_cita(cita_id)',
    f'V -> {API}: GET /citas/:id/trazabilidad',
    f'{API} -> {DAO}: obtener_historial_de_la_cita(cita_id)',
    *q('Bitacora_Auditoria', 'accion, momento_evento, datos_adicionales, usuario_id', 'N eventos'),
    f'{DAO} --> {API}: return (eventos ordenados del mas reciente al mas antiguo)',
    f'{API} --> V: return (HTTP 200 OK: historial de la cita)',
    'V --> A: desplegar_responsable_motivo_y_fecha_de_cada_cambio()',
  ],
  excepciones={
    1: dict(cortar='verificar_estado_no_terminal', lineas=[
        '! La cita ya posee un estado terminal no modificable',
        f'{API} ->> {API}: revertir_transaccion()',
        f'{API} --> V: return (HTTP 409 ESTADO_TERMINAL)',
        'V --> A: bloquear_edicion_y_mostrar_restriccion_de_flujo()',
        'A -> V: seleccionar_cita_valida(cita_id)'],
        reanudar='POST /citas/:id/transicionar'),
    2: dict(cortar='verificar_token_y_obtener_actor', lineas=[
        '! Perdida de contexto de la sesion: no se identifica al responsable',
        f'{API} ->> {API}: omitir_la_modificacion_de_la_cita()',
        f'{API} --> V: return (HTTP 401: advertencia de seguridad)',
        'V --> A: mostrar_advertencia_y_cerrar_sesion()',
        'A -> V: reiniciar_sesion_para_recuperar_credenciales()']),
    3: dict(cortar='exigir_justificacion_en_cancelacion_o_reprogramacion', lineas=[
        '! Campo de justificacion vacio en una cancelacion o reprogramacion',
        f'{API} ->> {API}: revertir_transaccion()',
        f'{API} --> V: return (HTTP 400 MOTIVO_REQUERIDO)',
        'V --> A: impedir_la_transicion_y_resaltar_campo_obligatorio()',
        'A -> V: redactar_motivo_del_cambio(motivo)'],
        reanudar='POST /citas/:id/transicionar'),
    4: dict(cortar='INSERT INTO Bitacora_Auditoria (accion', lineas=[
        *fallo_bd('Bitacora_Auditoria'),
        '! Fallo de persistencia durante el registro del log',
        f'{API} ->> {API}: revertir_la_operacion_completa()',
        f'{API} --> V: return (HTTP 500: el cambio no pudo aplicarse)',
        'V --> A: notificar_que_el_cambio_no_se_aplico()',
        'A -> V: reintentar_la_operacion()'],
        reanudar='POST /citas/:id/transicionar'),
  })

# ──────────────────────────── CU76 ────────────────────────────
CU76 = dict(id='CU76', nombre='Ejecutando transacciones en máquina de estados de la cita', actores=['Profesional'],
  vistas={'Profesional': 'V_Gestion_Agenda'},
  participantes=[ACTOR, VISTA, *BASE, T_CITA, P('Profesional', 'tabla'), P('Paquete_Sesiones', 'tabla'), T_BITACORA, T_NOTIF],
  principal=[
    'A -> V: seleccionar_cita_en_historial_del_paciente(cita_id)',
    'V ->> V: verificar_cita_propia_y_estado_no_terminal()',
    'V --> A: desplegar_acciones_de_transicion_habilitadas()',
    'A -> V: ejecutar_transicion(FINALIZAR)',
    f'V -> {API}: POST /citas/:id/transicionar (evento = FINALIZAR)',
    f'{API} -> {DAO}: abrir_transaccion_y_bloquear_cita(cita_id)',
    *q('Cita', 'cita_id, estado, paciente_id, profesional_id', '1 cita'),
    f'{DAO} --> {API}: return (cita)',
    f'{API} -> {DAO}: verificar_titularidad_del_profesional(usuario_id)',
    *q('Profesional', 'profesional_id, usuario_id', '1 coincidencia'),
    f'{DAO} --> {API}: return (cita propia)',
    f'{API} ->> {API}: evaluar_maquina_de_estados(CONFIRMADA | EN_CURSO -> REALIZADA)',
    f'{API} -> {DAO}: actualizar_estado(REALIZADA | INASISTENCIA)',
    *upd('Cita', 'estado'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} -> {DAO}: descontar_sesion_del_paquete(paciente_id)',
    *q('Paquete_Sesiones', 'paquete_sesiones_id, sesiones_total, sesiones_usadas', '1 paquete activo'),
    *upd('Paquete_Sesiones', 'sesiones_usadas'),
    f'{DAO} --> {API}: return (sesiones_restantes)',
    f'{API} -> {DAO}: registrar_trazabilidad(CITA_TRANSICIONADA, evento, responsable)',
    *ins('Bitacora_Auditoria'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} -> {DAO}: notificar_a_ambos_participantes(CAMBIO_ESTADO_CITA)',
    *ins('Notificacion', ' (aviso de cambio de estado)'),
    f'{DAO} --> {API}: return (Exito_Persistencia)',
    f'{API} ->> {API}: confirmar_transaccion()',
    f'{API} --> V: return (HTTP 200 OK: estado actualizado e inventario descontado)',
    'V --> A: mostrar_estado_de_la_cita_y_sesiones_restantes()',
  ],
  excepciones={
    1: dict(cortar='verificar_cita_propia_y_estado_no_terminal', lineas=[
        '! La cita pertenece a otro profesional',
        'V --> A: mostrar_cita_bloqueada_sin_controles_de_transicion()',
        'A -> V: seleccionar_cita_propia(cita_id)'],
        reanudar='verificar_cita_propia_y_estado_no_terminal'),
    2: dict(cortar='verificar_cita_propia_y_estado_no_terminal', lineas=[
        '! La cita ya posee un estado terminal',
        'V --> A: bloquear_modificaciones_y_mostrar_solo_lectura()',
        'A ->> A: revisar_el_estado_registrado()']),
    3: dict(cortar='desplegar_acciones_de_transicion_habilitadas', lineas=[
        '! El paciente no se presenta a la atencion',
        'A -> V: registrar_inasistencia()',
        f'V -> {API}: POST /citas/:id/transicionar (evento = REGISTRAR_INASISTENCIA)',
        f'{API} ->> {API}: aplicar_penalizacion_descontando_igualmente_la_sesion()'],
        reanudar='abrir_transaccion_y_bloquear_cita'),
    4: dict(cortar='SELECT paquete_sesiones_id', lineas=[
        f'Paquete_Sesiones --> {SQL}: return (0 paquetes activos)',
        f'{SQL} --> {DAO}: return (resultado)',
        f'{DAO} --> {API}: return (sin paquete activo)',
        '! El paciente no posee un paquete de sesiones activo',
        f'{API} ->> {API}: omitir_la_sustraccion_de_la_sesion()'],
        reanudar='registrar_trazabilidad(CITA_TRANSICIONADA'),
  })

if __name__ == '__main__':
    chrome = chrome_path()
    salida = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'salida')
    total = 0
    for cu in [CU17, CU18, CU22, CU76]:
        ruta, n = generar_cu(cu, os.path.join(salida, cu['id']), chrome=chrome, png=True)
        total += n; print(f"{cu['id']}: {n} paginas")
    print('total paginas', total)
